# Replace KV namespace IDs after running:
# wrangler kv namespace create "HISTORY"
# wrangler kv namespace create "THEMES"

name = "nowify-workers"
main = "workers/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "https://mechful.com"

routes = [
  { pattern = "nowify.mechful.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "HISTORY"
id = "5b9516f08cdb4e08a09759aacef112d1"
preview_id = "5b9516f08cdb4e08a09759aacef112d1"

[[kv_namespaces]]
binding = "THEMES"
id = "906ba770ea16408c96281935991e9d14"
preview_id = "906ba770ea16408c96281935991e9d14"
